version: '3.8'

services:

  mysql:
    image: mysql
    restart: always
    env_file: ./.env
    environment:
      MYSQL_ROOT_PASSWORD: $DB_PASSWORD
    ports:
      - 3306:3306

  backend:
    build: .
    container_name: backend
    depends_on:
      - mysql
    links:
      - mysql
    ports:
      - 3333:3333

